version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    image: docker/nginx
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - ./ideaconcert/venti/nginx:/etc/nginx.conf.d
  
  django:
    container_name: django
    build: ./ideaconcert
    image: docker/django
    command: gunicorn ideaconcert.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./ideaconcert:/srv/ideaconcert
      - ./ideaconcert:/var/log/uwsgi
    expose:
      - "8000"
    restart: always
